---

- name: Include vars in organisation.yml
  include_vars:
    file: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
  no_log: true

- name: Include vars in hosting_vars.yml
  include_vars:
    file: '/var/lib/awx/projects/hosting/hosting_vars.yml'
  no_log: true

- name: Include AWX master token from awx_tokens.yml
  include_vars:
    file: /var/lib/awx/projects/hosting/awx_tokens.yml
  no_log: true
